/**
 * AgencyCheck — Worker Review Seed Data
 * ~100 realistic reviews distributed across canonical agencies.
 *
 * Tone distribution:
 *   20% positive   (overallRating 4–5)
 *   50% mixed      (overallRating 3)
 *   30% negative   (overallRating 1–2)  ← factual, no extreme accusations
 *
 * Issue tags reference:
 *   housing_crowded | housing_good | housing_clean | housing_dirty
 *   late_salary | fair_pay | below_average_pay
 *   transport_good | transport_delays | no_transport
 *   missing_overtime | overtime_paid
 *   unclear_contract | fair_contract
 *   management_poor | management_ok | management_good
 *   payslip_errors | payslip_ok
 *   communication_poor | communication_good
 */

export interface ReviewSeed {
  agencySlug:            string;
  reviewType:            "ANONYMOUS" | "VERIFIED_WORKER";
  title:                 string;
  overallRating:         number;  // 1–5
  salaryRating:          number;
  housingRating?:        number | null;
  managementRating:      number;
  contractClarityRating: number;
  comment:               string;
  jobTitle?:             string | null;
  city?:                 string | null;
  issueTags:             string[];
  verificationStatus:    "VERIFIED" | "WORKER_REPORTED" | "UNKNOWN";
  sourceType:            "WORKER_REPORTED";
  createdAt:             string; // ISO date string
}

export const REVIEW_SEED_DATA: ReviewSeed[] = [

  // ── otto-work-force (housing YES, logistics, large) ──────────────────────────
  {
    agencySlug: "otto-work-force",
    reviewType: "VERIFIED_WORKER",
    title: "Good pay but housing was overcrowded",
    overallRating: 3,
    salaryRating: 4,
    housingRating: 2,
    managementRating: 3,
    contractClarityRating: 3,
    comment: "Salary was paid on time and the hourly rate is fair for warehouse work. The problem was the house — we were four people in a two-person room. Deduction was €95/week which is on the high side for the conditions. Management at the warehouse was decent, not much communication but they leave you alone.",
    jobTitle: "Warehouse Operative",
    city: "Venlo",
    issueTags: ["housing_crowded", "fair_pay"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-14",
  },
  {
    agencySlug: "otto-work-force",
    reviewType: "ANONYMOUS",
    title: "Transport reliable, contract explained well",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 3,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "The bus came on time every morning. The coordinator explained the ABU CAO at the start which I appreciated — not all agencies do this. Housing was shared but functional, nothing luxurious. Overall a reasonable agency for logistics work.",
    jobTitle: "Order Picker",
    city: "Tilburg",
    issueTags: ["transport_good", "fair_contract", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-20",
  },
  {
    agencySlug: "otto-work-force",
    reviewType: "ANONYMOUS",
    title: "Overtime not showing on payslip",
    overallRating: 2,
    salaryRating: 2,
    housingRating: 2,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Worked six weekends in a row and Sunday premium did not appear on my payslip. When I asked the contact person they said it would be corrected but nothing happened for three months. Housing was also not great — boiler broken for two weeks before it was fixed. I left after five months.",
    jobTitle: "Production Worker",
    city: "Venlo",
    issueTags: ["missing_overtime", "payslip_errors", "housing_dirty"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-05",
  },
  {
    agencySlug: "otto-work-force",
    reviewType: "VERIFIED_WORKER",
    title: "Solid agency, processes are clear",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "I have been with Otto for eight months now. Pay is always on time, the housing is a proper house with five other workers — clean kitchen, own room after a few months. They use a digital portal for shifts which is convenient.",
    jobTitle: "Forklift Driver",
    city: "Tilburg",
    issueTags: ["fair_pay", "housing_clean", "transport_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-01",
  },
  {
    agencySlug: "otto-work-force",
    reviewType: "ANONYMOUS",
    title: "Hours were cut with no warning",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 2,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "Was promised 40 hours per week but in reality I often got 28–32. The housing deduction stayed at full €95 even when I was only working part time. That makes it very hard to save money. No explanation from management — just told to be available and wait.",
    jobTitle: "Packing Operator",
    city: "Tilburg",
    issueTags: ["housing_crowded", "management_poor", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-10",
  },

  // ── foreignflex (housing YES, expat-focused) ─────────────────────────────────
  {
    agencySlug: "foreignflex",
    reviewType: "VERIFIED_WORKER",
    title: "Helped a lot with paperwork when I arrived",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 3,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "As a foreign worker, the registration process can be stressful. ForeignFlex helped with BSN registration and explained the contract in English. Salary was correct every month. Housing was a shared house — three people per room which is not ideal but it is what was agreed.",
    jobTitle: "Order Picker",
    city: "Rotterdam",
    issueTags: ["housing_crowded", "communication_good", "fair_pay"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-28",
  },
  {
    agencySlug: "foreignflex",
    reviewType: "ANONYMOUS",
    title: "Contract was in Dutch only",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 2,
    managementRating: 2,
    contractClarityRating: 1,
    comment: "The contract was given to me in Dutch and nobody offered a translation. I asked for an English version and was told it was not available. The housing deduction was €105 per week but the room had mould on the ceiling. I left after three months.",
    jobTitle: "Warehouse Worker",
    city: "Rotterdam",
    issueTags: ["unclear_contract", "housing_dirty", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-14",
  },
  {
    agencySlug: "foreignflex",
    reviewType: "ANONYMOUS",
    title: "Good for first months in the Netherlands",
    overallRating: 3,
    salaryRating: 3,
    housingRating: 3,
    managementRating: 3,
    contractClarityRating: 3,
    comment: "A reasonable start point if you just arrived. The housing is basic but it covers the initial period when you cannot yet rent privately. Salary is at WML level so do not expect much savings.",
    jobTitle: "Production Worker",
    city: "Rotterdam",
    issueTags: ["fair_pay"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-07-30",
  },
  {
    agencySlug: "foreignflex",
    reviewType: "ANONYMOUS",
    title: "Salary always on time, good team",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 4,
    contractClarityRating: 3,
    comment: "Never had a late payment in 14 months. The supervisor at the warehouse is fair. Housing could use some renovation but it is clean and safe. I would recommend if you work in the port area.",
    jobTitle: "Forklift Driver",
    city: "Rotterdam",
    issueTags: ["fair_pay", "housing_clean"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-03",
  },

  // ── ea-uitzendbureau-e-a-logistiek (housing YES, logistics) ──────────────────
  {
    agencySlug: "ea-uitzendbureau-e-a-logistiek",
    reviewType: "ANONYMOUS",
    title: "Housing deduction not clear in contract",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 2,
    managementRating: 2,
    contractClarityRating: 1,
    comment: "The contract mentioned housing but the weekly deduction was not stated clearly. I only found out it was €100/week after my first payslip. When I asked about it the coordinator was dismissive. Salary rate itself is okay but the hidden deduction makes it feel less.",
    jobTitle: "Warehouse Worker",
    city: "Amsterdam",
    issueTags: ["unclear_contract", "housing_crowded", "payslip_errors"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-08",
  },
  {
    agencySlug: "ea-uitzendbureau-e-a-logistiek",
    reviewType: "VERIFIED_WORKER",
    title: "Consistent work, on-time payments",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 3,
    contractClarityRating: 4,
    comment: "Ten months with this agency. Pay always arrives on the agreed day. Housing is a proper apartment split between four workers — reasonable for the price. Management at the client site can be demanding but that is the logistics industry.",
    jobTitle: "Reach Truck Driver",
    city: "Amsterdam",
    issueTags: ["fair_pay", "housing_good", "overtime_paid"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-12",
  },
  {
    agencySlug: "ea-uitzendbureau-e-a-logistiek",
    reviewType: "ANONYMOUS",
    title: "Three in one room, no kitchen privacy",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 1,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "Housing was three people sharing one room. The kitchen was shared between twelve workers which made it difficult in the mornings. For €95/week I expected at least a private room. The work itself at the warehouse was fine.",
    jobTitle: "Order Picker",
    city: "Amsterdam",
    issueTags: ["housing_crowded", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-18",
  },
  {
    agencySlug: "ea-uitzendbureau-e-a-logistiek",
    reviewType: "ANONYMOUS",
    title: "Good agency for long-term work",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 3,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "After six months they offered me a direct contract with the client. The agency is professional and straightforward. I appreciate that they always answered my questions about the contract. The housing was basic but acceptable.",
    jobTitle: "Forklift Driver",
    city: "Schiphol",
    issueTags: ["fair_pay", "management_good", "fair_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-03",
  },
  {
    agencySlug: "ea-uitzendbureau-e-a-logistiek",
    reviewType: "ANONYMOUS",
    title: "Payslip missing overtime for three months",
    overallRating: 1,
    salaryRating: 1,
    housingRating: 2,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "Overtime hours worked during holiday season were not on payslip for November, December, or January. Total missing was around €380. After many calls and emails I eventually received partial payment but never got the full amount. Would not recommend.",
    jobTitle: "Production Worker",
    city: "Amsterdam",
    issueTags: ["missing_overtime", "payslip_errors", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-25",
  },

  // ── flexdirect-uitzendgroep (housing YES) ────────────────────────────────────
  {
    agencySlug: "flexdirect-uitzendgroep",
    reviewType: "VERIFIED_WORKER",
    title: "Professional agency with good housing",
    overallRating: 5,
    salaryRating: 5,
    housingRating: 5,
    managementRating: 4,
    contractClarityRating: 5,
    comment: "By far the best agency I have worked with in the Netherlands. Private room, clean bathroom, fair salary with all overtime correctly paid. The contract was explained in detail and I received a copy translated to Polish. Cannot fault them.",
    jobTitle: "Reach Truck Driver",
    city: "Breda",
    issueTags: ["fair_pay", "housing_good", "fair_contract", "overtime_paid"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-18",
  },
  {
    agencySlug: "flexdirect-uitzendgroep",
    reviewType: "ANONYMOUS",
    title: "Housing good but transport could improve",
    overallRating: 3,
    salaryRating: 3,
    housingRating: 4,
    managementRating: 3,
    contractClarityRating: 3,
    comment: "The accommodation was genuinely good — two people per room, clean facilities. The main issue is the transport: the route takes 45 minutes each way to reach the warehouse because they pick up workers from multiple locations. Very tiring on early shifts.",
    jobTitle: "Packing Operator",
    city: "Breda",
    issueTags: ["housing_good", "transport_delays"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-22",
  },
  {
    agencySlug: "flexdirect-uitzendgroep",
    reviewType: "ANONYMOUS",
    title: "Pay rate below what was advertised",
    overallRating: 2,
    salaryRating: 2,
    housingRating: 3,
    managementRating: 2,
    contractClarityRating: 1,
    comment: "Advertised at €14.50/hr but after signing I discovered the actual rate was the WML minimum. When I raised this the response was that the advertised rate was for experienced workers. This was not explained at the recruitment stage.",
    jobTitle: "Warehouse Worker",
    city: "Tilburg",
    issueTags: ["unclear_contract", "below_average_pay", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-30",
  },
  {
    agencySlug: "flexdirect-uitzendgroep",
    reviewType: "VERIFIED_WORKER",
    title: "Steady work and fair treatment",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "I have been here a year. Nothing extraordinary but everything works as expected. Payslip is correct, overtime shows up, the house is kept clean. Management gives enough warning when shifts change. Would stay longer if the client location did not move.",
    jobTitle: "Logistics Operator",
    city: "Breda",
    issueTags: ["fair_pay", "housing_clean", "payslip_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-19",
  },

  // ── abflexkracht-uitzenden (housing YES) ─────────────────────────────────────
  {
    agencySlug: "abflexkracht-uitzenden",
    reviewType: "ANONYMOUS",
    title: "Decent but very basic accommodation",
    overallRating: 3,
    salaryRating: 3,
    housingRating: 2,
    managementRating: 3,
    contractClarityRating: 3,
    comment: "The agency itself is okay. Salary comes on time and the contact person responds to messages. The housing is quite basic — old furniture, shared bathrooms for too many people. For €90/week I expected something slightly better but it is liveable.",
    jobTitle: "Order Picker",
    city: "Tilburg",
    issueTags: ["housing_crowded", "fair_pay"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-15",
  },
  {
    agencySlug: "abflexkracht-uitzenden",
    reviewType: "ANONYMOUS",
    title: "Left after contract was changed without notice",
    overallRating: 1,
    salaryRating: 2,
    housingRating: 2,
    managementRating: 1,
    contractClarityRating: 1,
    comment: "My contract was changed from 40hr to 32hr without prior discussion. I found out when my salary was lower and then received a new contract to sign already backdated. I refused and left. Workers should always keep a copy of their original contract.",
    jobTitle: "Production Worker",
    city: "Eindhoven",
    issueTags: ["unclear_contract", "management_poor", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-11",
  },
  {
    agencySlug: "abflexkracht-uitzenden",
    reviewType: "VERIFIED_WORKER",
    title: "Reliable for logistics work",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 3,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Used them for a seven-month logistics contract. Pay was always correct, bonus for night shifts included. Housing was shared but functional and clean. Would use again for future contracts.",
    jobTitle: "Reach Truck Driver",
    city: "Tilburg",
    issueTags: ["fair_pay", "housing_clean", "overtime_paid"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-07",
  },
  {
    agencySlug: "abflexkracht-uitzenden",
    reviewType: "ANONYMOUS",
    title: "Slow response to questions",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 2,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Took three days to get a response when I had a payslip question. The housing had a broken heating system for six weeks in November and repeated requests did not lead to a quick fix. Pay was correct but the overall support is poor.",
    jobTitle: "Warehouse Worker",
    city: "Tilburg",
    issueTags: ["housing_dirty", "communication_poor", "payslip_errors"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-18",
  },

  // ── level-one (housing YES) ──────────────────────────────────────────────────
  {
    agencySlug: "level-one",
    reviewType: "VERIFIED_WORKER",
    title: "One of the better agencies I have tried",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 4,
    contractClarityRating: 5,
    comment: "Contract was translated into three languages, everything was clearly explained including the housing deduction schedule. Salary was €15/hr after probation which is fair. Housing was a two-person room — not private but very clean.",
    jobTitle: "Forklift Driver",
    city: "Almere",
    issueTags: ["fair_pay", "housing_clean", "fair_contract", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-07",
  },
  {
    agencySlug: "level-one",
    reviewType: "ANONYMOUS",
    title: "Transport breaks down too often",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 3,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "The bus to the factory is old and broke down twice in my first month. When that happens you still have to be present on time but there is no alternative provided. Missing a shift means losing a day pay. This was a real problem in winter.",
    jobTitle: "Production Worker",
    city: "Lelystad",
    issueTags: ["transport_delays", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-02",
  },
  {
    agencySlug: "level-one",
    reviewType: "VERIFIED_WORKER",
    title: "Excellent start for new arrivals to NL",
    overallRating: 5,
    salaryRating: 5,
    housingRating: 5,
    managementRating: 5,
    contractClarityRating: 5,
    comment: "They handled my DigiD application, BSN, and the housing registration all in one week. This kind of support is invaluable when you first arrive. Salary was above average and paid weekly which helped with initial costs. Strongly recommend.",
    jobTitle: "Logistics Operator",
    city: "Almere",
    issueTags: ["fair_pay", "housing_good", "communication_good", "fair_contract"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-08",
  },
  {
    agencySlug: "level-one",
    reviewType: "ANONYMOUS",
    title: "Work dried up after three months",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 3,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Was told there would be steady work. After three months the client reduced their order volume and suddenly I was only getting two or three shifts per week. Housing deduction stayed at full rate. The agency did not help find alternative placements quickly enough.",
    jobTitle: "Packing Operator",
    city: "Almere",
    issueTags: ["management_poor", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-22",
  },

  // ── ab-service-midden-nederland (housing YES) ────────────────────────────────
  {
    agencySlug: "ab-service-midden-nederland",
    reviewType: "VERIFIED_WORKER",
    title: "Pay accurate every time",
    overallRating: 4,
    salaryRating: 5,
    housingRating: 4,
    managementRating: 3,
    contractClarityRating: 4,
    comment: "In nine months I never had a payslip error. Overtime and Sunday rates are applied correctly. The house is shared with five other workers but has a proper kitchen and two bathrooms. Management could be more communicative about schedule changes.",
    jobTitle: "Reach Truck Driver",
    city: "Utrecht",
    issueTags: ["fair_pay", "housing_clean", "payslip_ok", "overtime_paid"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-31",
  },
  {
    agencySlug: "ab-service-midden-nederland",
    reviewType: "ANONYMOUS",
    title: "Contract extension denied without reason",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 3,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "Was expecting a contract extension based on discussions with my supervisor. Then two weeks before the end of my contract I was told it would not be renewed. No explanation given. Had to find housing and work at the same time which was very stressful.",
    jobTitle: "Order Picker",
    city: "Nieuwegein",
    issueTags: ["management_poor", "unclear_contract", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-17",
  },
  {
    agencySlug: "ab-service-midden-nederland",
    reviewType: "ANONYMOUS",
    title: "Recommended for reliable logistics contracts",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Professional and well organised. They provide a clear schedule two weeks in advance which makes planning easier. Pay includes all correct allowances. Good choice for warehouse work in the Utrecht area.",
    jobTitle: "Forklift Driver",
    city: "Utrecht",
    issueTags: ["fair_pay", "management_good", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-07-14",
  },

  // ── adecco-hr-solutions (large, well-known) ──────────────────────────────────
  {
    agencySlug: "adecco-hr-solutions",
    reviewType: "VERIFIED_WORKER",
    title: "Professional agency with good support",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 5,
    comment: "Adecco explained the contract fully and their online portal makes payslip checking easy. I arranged my own housing so cannot comment on that. Pay was always on time and above minimum wage. The onboarding process was professional.",
    jobTitle: "Logistics Operator",
    city: "Amsterdam",
    issueTags: ["fair_pay", "fair_contract", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-22",
  },
  {
    agencySlug: "adecco-hr-solutions",
    reviewType: "ANONYMOUS",
    title: "Missing Sunday premium for six weeks",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "Worked twelve Sundays over six weeks. The Sunday premium was not included on any of those payslips. After raising it I was told it would be corrected in the next period — it was eventually added but only after pushing multiple times. A large agency should have better processes for this.",
    jobTitle: "Packing Operator",
    city: "Rotterdam",
    issueTags: ["missing_overtime", "payslip_errors"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-10",
  },
  {
    agencySlug: "adecco-hr-solutions",
    reviewType: "VERIFIED_WORKER",
    title: "Strong digital tools make tracking easy",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "The app lets you see shifts, payslips, and contracts all in one place. Pay was always correct. The recruiters are responsive. Good choice if you want a large, established agency with structured processes.",
    jobTitle: "Forklift Driver",
    city: "Tilburg",
    issueTags: ["fair_pay", "payslip_ok", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-16",
  },
  {
    agencySlug: "adecco-hr-solutions",
    reviewType: "ANONYMOUS",
    title: "Rate dropped after probation ended",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 1,
    comment: "My hourly rate was reduced after the three-month review. The contract said salary could be 'adjusted based on performance' which I interpreted as a potential increase. The new rate was lower. I was not happy and the explanation from my coordinator was vague.",
    jobTitle: "Production Worker",
    city: "Eindhoven",
    issueTags: ["unclear_contract", "below_average_pay", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-28",
  },

  // ── actief-werkt ─────────────────────────────────────────────────────────────
  {
    agencySlug: "actief-werkt",
    reviewType: "ANONYMOUS",
    title: "Quick placement but minimal support",
    overallRating: 3,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "They placed me within a week which was good when I needed income fast. After placement the contact from the agency is minimal. You handle questions directly with the client site. Not ideal if you need guidance on Dutch employment rules.",
    jobTitle: "Packing Operator",
    city: "Eindhoven",
    issueTags: ["communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-09",
  },
  {
    agencySlug: "actief-werkt",
    reviewType: "VERIFIED_WORKER",
    title: "Flexible hours suited me well",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "As someone with family commitments I needed some schedule flexibility. Actief Werkt was willing to work with my availability. Pay was fair and the contract was simple. Good experience.",
    jobTitle: "Warehouse Worker",
    city: "Eindhoven",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-25",
  },
  {
    agencySlug: "actief-werkt",
    reviewType: "ANONYMOUS",
    title: "Payslip wrong twice in a row",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "For two consecutive months my payslip showed the wrong number of hours. Both times I had to call and correct it. The third month was fine. This is a simple administrative error that should not happen repeatedly at a professional agency.",
    jobTitle: "Order Picker",
    city: "Helmond",
    issueTags: ["payslip_errors", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-07-04",
  },
  {
    agencySlug: "actief-werkt",
    reviewType: "ANONYMOUS",
    title: "Contract not renewed at short notice",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "Was informed one week before the end of a three-month contract that it would not be extended. No prior indication this was coming. Left with very short notice to find alternatives.",
    jobTitle: "Logistics Operator",
    city: "Veldhoven",
    issueTags: ["management_poor", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-29",
  },

  // ── covebo ───────────────────────────────────────────────────────────────────
  {
    agencySlug: "covebo",
    reviewType: "VERIFIED_WORKER",
    title: "Top agency in South Netherlands",
    overallRating: 5,
    salaryRating: 5,
    housingRating: null,
    managementRating: 5,
    contractClarityRating: 5,
    comment: "Worked with Covebo for fourteen months. Best agency experience I have had in the Netherlands. Salary above WML, payslips always correct, coordinator responds same day. Strongly recommend for Eindhoven area logistics.",
    jobTitle: "Forklift Driver",
    city: "Eindhoven",
    issueTags: ["fair_pay", "payslip_ok", "communication_good", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-14",
  },
  {
    agencySlug: "covebo",
    reviewType: "ANONYMOUS",
    title: "Did not receive WML top-up when required",
    overallRating: 2,
    salaryRating: 1,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "In January 2025 the WML increased but my salary was not updated for two months. The agency eventually paid the difference after I brought it to their attention but workers should not have to chase this — it is a legal obligation.",
    jobTitle: "Packing Operator",
    city: "Helmond",
    issueTags: ["below_average_pay", "payslip_errors", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-04-02",
  },
  {
    agencySlug: "covebo",
    reviewType: "VERIFIED_WORKER",
    title: "Smooth process, reliable payments",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Eight months and no issues. The digital timesheet system is accurate and payslips reflect what was worked. Good agency for production and logistics work in Brabant.",
    jobTitle: "Reach Truck Driver",
    city: "Eindhoven",
    issueTags: ["fair_pay", "payslip_ok", "management_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-30",
  },

  // ── driessen ─────────────────────────────────────────────────────────────────
  {
    agencySlug: "driessen",
    reviewType: "ANONYMOUS",
    title: "Good for public sector and healthcare",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Driessen is strong in public sector and care roles. My contract included all CAO terms clearly. Pay was on time every month. Communication from the account manager was professional.",
    jobTitle: "Logistics Operator",
    city: "Den Bosch",
    issueTags: ["fair_pay", "fair_contract", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-14",
  },
  {
    agencySlug: "driessen",
    reviewType: "VERIFIED_WORKER",
    title: "Transparent from the start",
    overallRating: 5,
    salaryRating: 5,
    housingRating: null,
    managementRating: 5,
    contractClarityRating: 5,
    comment: "Everything was clear from day one: hourly rate, how overtime is calculated, holiday accrual. I have never had to ask twice about anything. The account manager is responsive and professional. Very positive experience.",
    jobTitle: "Warehouse Worker",
    city: "Den Bosch",
    issueTags: ["fair_pay", "management_good", "fair_contract", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-05",
  },

  // ── dailyflex-personeelsdiensten ─────────────────────────────────────────────
  {
    agencySlug: "dailyflex-personeelsdiensten",
    reviewType: "ANONYMOUS",
    title: "Daily availability required which is stressful",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "You have to confirm your availability each day by 7am. If you miss the window you do not get a shift. This level of uncertainty is very difficult if you have any other obligations. The pay rate is decent but the working model does not suit most people.",
    jobTitle: "Packing Operator",
    city: "Tilburg",
    issueTags: ["unclear_contract", "management_poor", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-28",
  },
  {
    agencySlug: "dailyflex-personeelsdiensten",
    reviewType: "ANONYMOUS",
    title: "Great if you want truly flexible work",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "For my situation — studying part time — the daily flex model is perfect. I choose my own days, pay is good, payment is every week. Not for everyone but works well for me.",
    jobTitle: "Warehouse Worker",
    city: "Tilburg",
    issueTags: ["fair_pay", "management_ok"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-19",
  },
  {
    agencySlug: "dailyflex-personeelsdiensten",
    reviewType: "ANONYMOUS",
    title: "Hours cut without explanation",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Was given many shifts in the first two months then suddenly very few with no explanation. Tried to get information and the response was just that shifts depend on demand. Very unpredictable for anyone who needs stable income.",
    jobTitle: "Order Picker",
    city: "Breda",
    issueTags: ["management_poor", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-06",
  },
  {
    agencySlug: "dailyflex-personeelsdiensten",
    reviewType: "VERIFIED_WORKER",
    title: "Weekly pay and fair hourly rate",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 3,
    contractClarityRating: 4,
    comment: "Getting paid weekly is a real advantage. The rate is above WML. App for booking shifts works reliably. Only minor complaint is the communication from dispatchers could be faster.",
    jobTitle: "Logistics Operator",
    city: "Tilburg",
    issueTags: ["fair_pay", "payslip_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-26",
  },

  // ── cirrus-flexible-staffing ──────────────────────────────────────────────────
  {
    agencySlug: "cirrus-flexible-staffing",
    reviewType: "ANONYMOUS",
    title: "Good agency, responsive and fair",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Placed me in three months. Salary always correct. My questions about the ABU CAO were answered properly. Good for logistics and warehouse work in the Rotterdam area.",
    jobTitle: "Forklift Driver",
    city: "Rotterdam",
    issueTags: ["fair_pay", "management_good", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-07",
  },
  {
    agencySlug: "cirrus-flexible-staffing",
    reviewType: "ANONYMOUS",
    title: "Transport issues caused missed shifts",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "The transport van was late three times in two months causing me to miss parts of my shifts. Each time my pay was docked for the missed time even though it was not my fault. The agency said it was a contractor issue and not their responsibility.",
    jobTitle: "Warehouse Worker",
    city: "Rotterdam",
    issueTags: ["transport_delays", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-15",
  },

  // ── best-flex ────────────────────────────────────────────────────────────────
  {
    agencySlug: "best-flex",
    reviewType: "ANONYMOUS",
    title: "Late salary in October",
    overallRating: 2,
    salaryRating: 1,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "Salary was three days late in October with no explanation given in advance. When I asked about it I was told there was a bank processing issue. This was the first time but it caused problems with my rent payment. Salary should always be on time.",
    jobTitle: "Warehouse Worker",
    city: "Best",
    issueTags: ["late_salary", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-28",
  },
  {
    agencySlug: "best-flex",
    reviewType: "VERIFIED_WORKER",
    title: "Good local agency for Eindhoven region",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "A smaller, local agency with personal service. My coordinator knows my name and situation. Pay was correct and above minimum wage. Good for the Eindhoven and Best corridor.",
    jobTitle: "Forklift Driver",
    city: "Best",
    issueTags: ["fair_pay", "management_good", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-04",
  },
  {
    agencySlug: "best-flex",
    reviewType: "ANONYMOUS",
    title: "Promised training that never happened",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "During recruitment I was told there would be a forklift certification course included. After starting work I was told the course was on hold and they would let me know. Three months later still no course. Felt misled.",
    jobTitle: "Warehouse Worker",
    city: "Eindhoven",
    issueTags: ["management_poor", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-17",
  },

  // ── de-werkunie ───────────────────────────────────────────────────────────────
  {
    agencySlug: "de-werkunie",
    reviewType: "ANONYMOUS",
    title: "Union-affiliated agency, very transparent",
    overallRating: 5,
    salaryRating: 5,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 5,
    comment: "The most transparent agency I have encountered. They proactively explained workers' rights, how the ABU CAO applies to my contract, and what deductions are legal. Pay is consistently above average. Strongly recommend.",
    jobTitle: "Logistics Operator",
    city: "Amsterdam",
    issueTags: ["fair_pay", "fair_contract", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-16",
  },
  {
    agencySlug: "de-werkunie",
    reviewType: "VERIFIED_WORKER",
    title: "Long process but worth it",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "The intake process was more thorough than other agencies — they verified my qualifications and took time to understand what kind of work I was looking for. This led to a better placement. Pay above market.",
    jobTitle: "Reach Truck Driver",
    city: "Haarlem",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-22",
  },

  // ── attract-flex ──────────────────────────────────────────────────────────────
  {
    agencySlug: "attract-flex",
    reviewType: "ANONYMOUS",
    title: "Rushed onboarding, poor follow-up",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "Onboarding was done very fast. I signed a lot of documents without enough time to read them. Afterwards when I had questions the recruiter was not reachable. Pay was correct but the support structure is poor.",
    jobTitle: "Production Worker",
    city: "Utrecht",
    issueTags: ["unclear_contract", "communication_poor", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-21",
  },
  {
    agencySlug: "attract-flex",
    reviewType: "VERIFIED_WORKER",
    title: "Competitive rates in Utrecht",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Better hourly rate than most agencies offering work at the same client. The recruiter was approachable and kept in touch during the contract. Would use again.",
    jobTitle: "Forklift Driver",
    city: "Utrecht",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-03",
  },
  {
    agencySlug: "attract-flex",
    reviewType: "ANONYMOUS",
    title: "Night shift premium not applied",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Worked fifteen night shifts and none had the correct night-time supplement on the payslip. Had to chase this for over a month. The ABU CAO is clear that night shifts must be compensated — workers should check their contracts carefully.",
    jobTitle: "Warehouse Worker",
    city: "Utrecht",
    issueTags: ["missing_overtime", "payslip_errors", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-07-25",
  },

  // ── easy-way-flex ─────────────────────────────────────────────────────────────
  {
    agencySlug: "easy-way-flex",
    reviewType: "ANONYMOUS",
    title: "Name is accurate — straightforward process",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Simple, no-nonsense agency. Contract was one page and easy to understand. Pay is on time. Not the highest rate but also no unpleasant surprises.",
    jobTitle: "Order Picker",
    city: "Haarlem",
    issueTags: ["fair_pay", "fair_contract", "management_ok"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-12",
  },
  {
    agencySlug: "easy-way-flex",
    reviewType: "VERIFIED_WORKER",
    title: "Good for experienced warehouse workers",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "They were interested in my experience and placed me in a role above basic picker. Pay reflects the additional responsibility. Professional handling from start to finish.",
    jobTitle: "Logistics Operator",
    city: "Haarlem",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-20",
  },
  {
    agencySlug: "easy-way-flex",
    reviewType: "ANONYMOUS",
    title: "No issues in nine months",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Nine months of reliable work with no significant problems. Payslips correct, shifts as agreed, coordinator available when needed. A solid, boring agency — which is exactly what you want.",
    jobTitle: "Forklift Driver",
    city: "Amsterdam",
    issueTags: ["fair_pay", "payslip_ok"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-09",
  },

  // ── effect-uitzendbureau ──────────────────────────────────────────────────────
  {
    agencySlug: "effect-uitzendbureau",
    reviewType: "ANONYMOUS",
    title: "Hard to reach when problems arise",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "When my hours were incorrectly logged I tried calling and emailing for five days before someone responded. The issue was eventually fixed but for a payslip problem it should not take that long. The pay rate is fair but support is poor.",
    jobTitle: "Production Worker",
    city: "Rotterdam",
    issueTags: ["communication_poor", "payslip_errors", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-04",
  },
  {
    agencySlug: "effect-uitzendbureau",
    reviewType: "VERIFIED_WORKER",
    title: "Strong in Rotterdam logistics",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Worked six months at a major Rotterdam port client through Effect. Pay was on time and accurate. The recruiter had good knowledge of the port industry which made the placement better suited to my skills.",
    jobTitle: "Forklift Driver",
    city: "Rotterdam",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-30",
  },

  // ── befaflex ─────────────────────────────────────────────────────────────────
  {
    agencySlug: "befaflex",
    reviewType: "ANONYMOUS",
    title: "Housing conditions need improvement",
    overallRating: 2,
    salaryRating: 3,
    housingRating: 1,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "The work and pay were fine but the housing conditions were very poor. Broken windows in winter, no proper heating in the common area, and shared bathrooms for too many residents. Not acceptable for the amount being deducted.",
    jobTitle: "Warehouse Worker",
    city: "Venlo",
    issueTags: ["housing_dirty", "housing_crowded", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-13",
  },
  {
    agencySlug: "befaflex",
    reviewType: "VERIFIED_WORKER",
    title: "Good rate, clean house",
    overallRating: 4,
    salaryRating: 4,
    housingRating: 4,
    managementRating: 4,
    contractClarityRating: 3,
    comment: "My experience was positive. The house was clean and well maintained. Pay was €14.80/hr which is reasonable. The contract could be clearer on overtime terms but nothing was actually wrong with what I received.",
    jobTitle: "Reach Truck Driver",
    city: "Venlo",
    issueTags: ["fair_pay", "housing_clean"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-11",
  },

  // ── care4flex ─────────────────────────────────────────────────────────────────
  {
    agencySlug: "care4flex",
    reviewType: "ANONYMOUS",
    title: "Good for care sector placements",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Specialises in care and healthcare. My coordinator had experience in the sector and understood the demands of shift work in healthcare. Pay was correct and included all applicable supplements.",
    jobTitle: "Logistics Operator",
    city: "Utrecht",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-26",
  },
  {
    agencySlug: "care4flex",
    reviewType: "ANONYMOUS",
    title: "Weekend rate missing from November payslip",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 3,
    contractClarityRating: 2,
    comment: "Worked four weekends in November but the Saturday and Sunday supplements were not on my payslip. It was corrected in December after I raised it. Should not happen but at least it was fixed.",
    jobTitle: "Production Worker",
    city: "Utrecht",
    issueTags: ["missing_overtime", "payslip_errors"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-03",
  },
  {
    agencySlug: "care4flex",
    reviewType: "VERIFIED_WORKER",
    title: "Professional and caring as the name suggests",
    overallRating: 5,
    salaryRating: 5,
    housingRating: null,
    managementRating: 5,
    contractClarityRating: 5,
    comment: "Care4Flex genuinely cares about worker welfare. They checked in proactively each month to ensure my placement was going well. Pay was above average and always on time. Best agency I have worked with.",
    jobTitle: "Packing Operator",
    city: "Amsterdam",
    issueTags: ["fair_pay", "communication_good", "management_good", "fair_contract"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-20",
  },

  // ── axiflex ───────────────────────────────────────────────────────────────────
  {
    agencySlug: "axiflex",
    reviewType: "VERIFIED_WORKER",
    title: "Fast placement, correct pay",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "I was placed within five days and started working the following week. Payslips were always accurate including the first one. A straightforward, professional agency.",
    jobTitle: "Forklift Driver",
    city: "Dordrecht",
    issueTags: ["fair_pay", "management_ok", "payslip_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-29",
  },
  {
    agencySlug: "axiflex",
    reviewType: "ANONYMOUS",
    title: "Contract terminated early without explanation",
    overallRating: 1,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "My contract had three months remaining when I was told the placement was ending. No reason was given and the process felt arbitrary. Workers should be told clearly when and why placements end so they can plan.",
    jobTitle: "Warehouse Worker",
    city: "Rotterdam",
    issueTags: ["management_poor", "unclear_contract", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-24",
  },

  // ── 365werk ───────────────────────────────────────────────────────────────────
  {
    agencySlug: "365werk",
    reviewType: "ANONYMOUS",
    title: "Works well for year-round availability",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "As the name says they have year-round work. Pay was consistent and above minimum wage. The agency was upfront about the type of work and conditions. Good experience.",
    jobTitle: "Production Worker",
    city: "Tilburg",
    issueTags: ["fair_pay", "management_ok"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-15",
  },
  {
    agencySlug: "365werk",
    reviewType: "ANONYMOUS",
    title: "Payslip missing holiday accrual",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "After four months I noticed that my holiday hours were not showing on my payslip. When I asked they said it accumulates separately and pays out differently. The contract did not explain this clearly and I felt that important information was withheld.",
    jobTitle: "Order Picker",
    city: "Breda",
    issueTags: ["payslip_errors", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-13",
  },

  // ── flux-employment ───────────────────────────────────────────────────────────
  {
    agencySlug: "flex-employment",
    reviewType: "ANONYMOUS",
    title: "Coordinator changed three times in two months",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "I had three different coordinators in my first two months which made communication difficult. Each time I had to re-explain my situation. Pay was fine but the internal turnover at the agency itself is concerning.",
    jobTitle: "Logistics Operator",
    city: "Eindhoven",
    issueTags: ["communication_poor", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-02",
  },

  // ── a-flex ────────────────────────────────────────────────────────────────────
  {
    agencySlug: "a-flex",
    reviewType: "ANONYMOUS",
    title: "Positive experience in warehouse role",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 3,
    comment: "Pay was always correct and above the minimum. The coordinator responded quickly to questions. Only issue was the contract had some unclear clauses about notice period but nothing that caused practical problems.",
    jobTitle: "Order Picker",
    city: "Haarlem",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-23",
  },

  // ── gi-group-temp (international staffing, logistics focus) ──────────────────
  {
    agencySlug: "gi-group-temp",
    reviewType: "VERIFIED_WORKER",
    title: "Professional handling, above-average pay",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Gi Group is more structured than most agencies I have worked with. The onboarding included a clear explanation of the CAO terms and salary scale. Pay was €14.80/hr which is decent for picking work. No payslip issues in seven months.",
    jobTitle: "Order Picker",
    city: "Amsterdam",
    issueTags: ["fair_pay", "fair_contract", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-09",
  },
  {
    agencySlug: "gi-group-temp",
    reviewType: "ANONYMOUS",
    title: "Overtime missing for two months",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "December and January overtime hours were not on my payslips. I raised it twice before it was corrected. The amounts were not small — roughly €290 in total. For an international agency this admin standard is not good enough.",
    jobTitle: "Packing Operator",
    city: "Tilburg",
    issueTags: ["missing_overtime", "payslip_errors"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-27",
  },
  {
    agencySlug: "gi-group-temp",
    reviewType: "VERIFIED_WORKER",
    title: "Best experience in three years of agency work",
    overallRating: 5,
    salaryRating: 5,
    housingRating: null,
    managementRating: 5,
    contractClarityRating: 5,
    comment: "The coordinator genuinely knew the client site and the work conditions before placing me. Pay was above market and all supplements — night, Sunday, overtime — appeared correctly every month. The whole setup felt professional.",
    jobTitle: "Forklift Driver",
    city: "Amsterdam",
    issueTags: ["fair_pay", "payslip_ok", "management_good", "communication_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-31",
  },

  // ── altiflex-personeelsdiensten (Tilburg region, logistics) ──────────────────
  {
    agencySlug: "altiflex-personeelsdiensten",
    reviewType: "ANONYMOUS",
    title: "Salary was three days late in September",
    overallRating: 2,
    salaryRating: 1,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "September salary arrived three days late. When I asked about it the explanation was a bank issue. No apology was given. Subsequent months were on time. For a professional agency this should never happen.",
    jobTitle: "Production Worker",
    city: "Tilburg",
    issueTags: ["late_salary", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-28",
  },
  {
    agencySlug: "altiflex-personeelsdiensten",
    reviewType: "VERIFIED_WORKER",
    title: "Fair agency, responsive coordinator",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "My coordinator answered messages the same day and kept me informed about schedule changes. Pay was always correct and included night-shift supplement without needing to chase it. Solid choice for the Tilburg area.",
    jobTitle: "Reach Truck Driver",
    city: "Tilburg",
    issueTags: ["fair_pay", "management_good", "payslip_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-10-14",
  },
  {
    agencySlug: "altiflex-personeelsdiensten",
    reviewType: "ANONYMOUS",
    title: "Contract terms on overtime were vague",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 1,
    comment: "The overtime clause in my contract just said 'as per company policy' without any rate stated. When I worked overtime the added pay was lower than what I expected from the ABU CAO. After asking I got a partial correction but not the full difference.",
    jobTitle: "Packing Operator",
    city: "Waalwijk",
    issueTags: ["unclear_contract", "missing_overtime", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-07-15",
  },

  // ── afs-uitzendbureau (Schiphol / airport logistics) ─────────────────────────
  {
    agencySlug: "afs-uitzendbureau",
    reviewType: "VERIFIED_WORKER",
    title: "Good for Schiphol logistics roles",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "AFS specialises in Schiphol area placements and it shows — they know the work environment and the specific requirements for airside access. Pay was above average. Good choice if you want airport or cargo logistics work.",
    jobTitle: "Logistics Operator",
    city: "Schiphol",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-17",
  },
  {
    agencySlug: "afs-uitzendbureau",
    reviewType: "ANONYMOUS",
    title: "Hours reduced with no notice",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Was on 40 hours but after two months the client asked for fewer workers. My hours dropped to 24 without a proper explanation or conversation. The agency said it was client-driven but I had to figure out housing costs on fewer earnings. Very stressful.",
    jobTitle: "Packing Operator",
    city: "Hoofddorp",
    issueTags: ["management_poor", "communication_poor", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-11",
  },
  {
    agencySlug: "afs-uitzendbureau",
    reviewType: "ANONYMOUS",
    title: "Steady work, correct pay every month",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Eleven months at a cargo facility through AFS. Payslip was accurate every time. The coordinator responded within a day to questions. Good agency for airport freight and logistics.",
    jobTitle: "Forklift Driver",
    city: "Schiphol",
    issueTags: ["fair_pay", "payslip_ok", "management_ok"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-21",
  },

  // ── allroad-projecten (Eindhoven area) ────────────────────────────────────────
  {
    agencySlug: "allroad-projecten",
    reviewType: "ANONYMOUS",
    title: "Shift cancelled the night before twice",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 2,
    comment: "Had two shifts cancelled the evening before with no compensation. I had already arranged transport. The contract said shifts could be cancelled with short notice but I did not expect it to happen so regularly. Hard to plan your life around this.",
    jobTitle: "Warehouse Worker",
    city: "Eindhoven",
    issueTags: ["management_poor", "unclear_contract", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-26",
  },

  // ── factory4work (warehouse and production) ───────────────────────────────────
  {
    agencySlug: "factory4work",
    reviewType: "VERIFIED_WORKER",
    title: "Fast placement, pay always correct",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Started working within a week of registering. Payslips were accurate from the first month. The agency communicates schedule information clearly through their app. Good for anyone needing to start warehouse work quickly.",
    jobTitle: "Warehouse Worker",
    city: "Rotterdam",
    issueTags: ["fair_pay", "payslip_ok", "management_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-08",
  },
  {
    agencySlug: "factory4work",
    reviewType: "ANONYMOUS",
    title: "WML only, no extras",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 3,
    contractClarityRating: 3,
    comment: "Pay is strictly at the minimum wage level. The contract does not include any bonus or progression. For someone with warehouse experience this feels low. Nothing illegal but not competitive. I moved on after three months.",
    jobTitle: "Order Picker",
    city: "Rotterdam",
    issueTags: ["below_average_pay"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-07-21",
  },

  // ── easyworx-flex ─────────────────────────────────────────────────────────────
  {
    agencySlug: "easyworx-flex",
    reviewType: "ANONYMOUS",
    title: "Night supplement missing for six weeks",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "Worked six weeks of nights and the supplement did not appear on any payslip. When I reported it I was told the timesheet system had an error. It was eventually paid back but in full only after I sent a written complaint. Not acceptable.",
    jobTitle: "Warehouse Worker",
    city: "Amsterdam",
    issueTags: ["missing_overtime", "payslip_errors", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-06",
  },
  {
    agencySlug: "easyworx-flex",
    reviewType: "VERIFIED_WORKER",
    title: "Professional agency near Haarlem",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Six months working through Easyworx and no complaints. Pay was €14.50/hr, correct every time. The coordinator checked in monthly which I found reassuring. Good for the Haarlem logistics corridor.",
    jobTitle: "Logistics Operator",
    city: "Haarlem",
    issueTags: ["fair_pay", "management_good", "payslip_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-27",
  },
  {
    agencySlug: "easyworx-flex",
    reviewType: "ANONYMOUS",
    title: "Contract signed under pressure",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 1,
    comment: "I was given the contract and told I had to sign that day to secure the placement. There was no time to read it properly. A week later I noticed the notice period clause was very unfavourable. Workers need time to read contracts before signing.",
    jobTitle: "Packing Operator",
    city: "Amsterdam",
    issueTags: ["unclear_contract", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-06-17",
  },
  {
    agencySlug: "easyworx-flex",
    reviewType: "ANONYMOUS",
    title: "Straightforward and honest agency",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Eight months, no issues. The agency told me clearly what rate I would get and did not change it after signing. Payslips match what was worked. Simple and honest — that is what I look for.",
    jobTitle: "Forklift Driver",
    city: "Amsterdam",
    issueTags: ["fair_pay", "fair_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-30",
  },

  // ── impact-personeel ──────────────────────────────────────────────────────────
  {
    agencySlug: "impact-personeel",
    reviewType: "VERIFIED_WORKER",
    title: "Above market rate, good processes",
    overallRating: 4,
    salaryRating: 5,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Impact was paying €15.20/hr for the same role other agencies offered at €13.68. They explained this was a client rate negotiated separately. Payslip was accurate and overtime was included correctly. Strongly positive experience.",
    jobTitle: "Production Worker",
    city: "Eindhoven",
    issueTags: ["fair_pay", "payslip_ok", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-08",
  },
  {
    agencySlug: "impact-personeel",
    reviewType: "ANONYMOUS",
    title: "Holiday pay not included for three months",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "The 8% vakantiegeld did not show on my payslip for the first three months. When I noticed and asked, they confirmed it would be paid out in June only. The contract did not make this clear. Workers should always check if vakantiegeld is monthly or annual.",
    jobTitle: "Packing Operator",
    city: "Eindhoven",
    issueTags: ["payslip_errors", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-04-29",
  },

  // ── europlus ──────────────────────────────────────────────────────────────────
  {
    agencySlug: "europlus",
    reviewType: "VERIFIED_WORKER",
    title: "Strong in Rotterdam port logistics",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Europlus has good relationships with the port clients in Rotterdam. They placed me quickly in a reach-truck role at €15/hr. Pay was always on time and the coordinator knew the port environment well.",
    jobTitle: "Reach Truck Driver",
    city: "Rotterdam",
    issueTags: ["fair_pay", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-22",
  },
  {
    agencySlug: "europlus",
    reviewType: "ANONYMOUS",
    title: "Salary late in November, no explanation",
    overallRating: 2,
    salaryRating: 1,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "November salary was four days late. No message was sent to workers explaining why. I had direct debit payments set up so this caused a banking fee. A single message in advance would have been the minimum.",
    jobTitle: "Packing Operator",
    city: "Rotterdam",
    issueTags: ["late_salary", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-05",
  },
  {
    agencySlug: "europlus",
    reviewType: "ANONYMOUS",
    title: "Pay above average, good communication",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "The rate was €14.80/hr for forklift work which is on the better end. My coordinator responded quickly and kept me updated when there were shifts available. Would use again for the Dordrecht and Rotterdam area.",
    jobTitle: "Forklift Driver",
    city: "Dordrecht",
    issueTags: ["fair_pay", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-12",
  },

  // ── faber-personeelsdiensten ──────────────────────────────────────────────────
  {
    agencySlug: "faber-personeelsdiensten",
    reviewType: "ANONYMOUS",
    title: "Regional agency with personal service",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "A smaller, traditional agency. The coordinator knows my name and what kind of work I prefer. Pay is fair and consistent. Personal service makes a difference when you have questions — response time is same-day.",
    jobTitle: "Production Worker",
    city: "Groningen",
    issueTags: ["fair_pay", "communication_good", "management_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-14",
  },
  {
    agencySlug: "faber-personeelsdiensten",
    reviewType: "VERIFIED_WORKER",
    title: "Consistent work for over a year",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Thirteen months and the agency has been professional throughout. Pay correct, overtime applied, coordinator available. The local focus means they understand the regional job market well.",
    jobTitle: "Reach Truck Driver",
    city: "Groningen",
    issueTags: ["fair_pay", "payslip_ok", "management_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-29",
  },

  // ── continu ───────────────────────────────────────────────────────────────────
  {
    agencySlug: "continu",
    reviewType: "VERIFIED_WORKER",
    title: "Very positive twelve-month experience",
    overallRating: 5,
    salaryRating: 5,
    housingRating: null,
    managementRating: 5,
    contractClarityRating: 5,
    comment: "Continu has been the best agency I have worked with. Salary above minimum, payslip explained clearly from the start, and the coordinator was genuinely helpful when I had a health-related absence. Would recommend without hesitation.",
    jobTitle: "Forklift Driver",
    city: "Amsterdam",
    issueTags: ["fair_pay", "payslip_ok", "management_good", "fair_contract"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-02-15",
  },
  {
    agencySlug: "continu",
    reviewType: "ANONYMOUS",
    title: "Contract clause I did not understand about exclusivity",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 1,
    comment: "The contract had an exclusivity clause preventing me from working through another agency during the placement. This was not mentioned at the recruitment stage. When the hours dropped below 30/week I could not top up my income elsewhere. This should be communicated upfront.",
    jobTitle: "Warehouse Worker",
    city: "Amsterdam",
    issueTags: ["unclear_contract", "management_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-08",
  },
  {
    agencySlug: "continu",
    reviewType: "ANONYMOUS",
    title: "Above-average pay, prompt responses",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "€15/hr for warehouse picking which is above what most agencies offer for this type of role. Messages returned same day. Payslip correct. A good agency with a professional attitude.",
    jobTitle: "Order Picker",
    city: "Amsterdam",
    issueTags: ["fair_pay", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-12-13",
  },

  // ── flexsupport ───────────────────────────────────────────────────────────────
  {
    agencySlug: "flexsupport",
    reviewType: "VERIFIED_WORKER",
    title: "Solid agency for Rotterdam logistics",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Eight months through Flexsupport at a Rotterdam distribution centre. Pay was always correct and the Sunday supplement was applied automatically without needing to request it. Clear contract, good coordinator.",
    jobTitle: "Forklift Driver",
    city: "Rotterdam",
    issueTags: ["fair_pay", "payslip_ok", "management_ok"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-11-03",
  },
  {
    agencySlug: "flexsupport",
    reviewType: "ANONYMOUS",
    title: "Hours on payslip did not match worked hours",
    overallRating: 2,
    salaryRating: 2,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 3,
    comment: "In April the payslip showed 156 hours but I had worked 172 according to my own log. Raised it and received a correction in May. I now keep my own record every day. Workers should not have to verify the agency's timekeeping.",
    jobTitle: "Warehouse Worker",
    city: "Utrecht",
    issueTags: ["payslip_errors", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-05-22",
  },
  {
    agencySlug: "flexsupport",
    reviewType: "ANONYMOUS",
    title: "Good rate for experienced warehouse workers",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "Offered €15.25/hr after discussing my reach-truck experience which is above what I was getting previously. The contract included a clear pay scale for progression after six months. Professional handling.",
    jobTitle: "Reach Truck Driver",
    city: "Rotterdam",
    issueTags: ["fair_pay", "fair_contract", "management_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-18",
  },
  {
    agencySlug: "flexsupport",
    reviewType: "ANONYMOUS",
    title: "Management at warehouse was the real problem",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 3,
    comment: "The agency itself was fine — pay on time, contract clear. The issue was the client-side supervisor who treated agency workers differently from permanent staff. Reported it to the agency who said it was outside their control. This is a common agency worker problem.",
    jobTitle: "Order Picker",
    city: "Utrecht",
    issueTags: ["management_poor", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-16",
  },

  // ── actief-werkt-uitzendbureau-bv (Breda) ────────────────────────────────────
  {
    agencySlug: "actief-werkt-uitzendbureau-bv",
    reviewType: "VERIFIED_WORKER",
    title: "Positive seven-month experience in Breda",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "My coordinator was easy to reach and solved a payslip question quickly. Hours were consistent at 40 per week. Pay included correct Sunday and overtime rates. Would use again for Breda area work.",
    jobTitle: "Warehouse Worker",
    city: "Breda",
    issueTags: ["fair_pay", "payslip_ok", "management_good"],
    verificationStatus: "VERIFIED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2026-01-25",
  },
  {
    agencySlug: "actief-werkt-uitzendbureau-bv",
    reviewType: "ANONYMOUS",
    title: "Hours not guaranteed, schedule changes late",
    overallRating: 2,
    salaryRating: 3,
    housingRating: null,
    managementRating: 2,
    contractClarityRating: 2,
    comment: "The schedule is sometimes published only two days before the week starts. For someone with family it is very hard to plan. I was promised around 38 hours but some weeks got as few as 22. The agency said it depended on the client's order volume.",
    jobTitle: "Production Worker",
    city: "Breda",
    issueTags: ["management_poor", "unclear_contract"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-08-14",
  },

  // ── basic-interim ─────────────────────────────────────────────────────────────
  {
    agencySlug: "basic-interim",
    reviewType: "ANONYMOUS",
    title: "Good first agency in the Netherlands",
    overallRating: 4,
    salaryRating: 4,
    housingRating: null,
    managementRating: 4,
    contractClarityRating: 4,
    comment: "As a new arrival the straightforward approach was helpful. No complex structure, clear contract, honest about what to expect. Pay was slightly above WML. A good starting point before moving to a more specialist agency.",
    jobTitle: "Warehouse Worker",
    city: "Haarlem",
    issueTags: ["fair_pay", "fair_contract", "communication_good"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-05-31",
  },
  {
    agencySlug: "basic-interim",
    reviewType: "ANONYMOUS",
    title: "Contract changed without informing me",
    overallRating: 1,
    salaryRating: 2,
    housingRating: null,
    managementRating: 1,
    contractClarityRating: 1,
    comment: "Received a new contract version in the post. The hours were lower and the rate was different from what I had signed. When I called to ask about it the explanation was that the previous version had an error. I refused to sign and left. Always keep a copy of your original contract.",
    jobTitle: "Logistics Operator",
    city: "Amsterdam",
    issueTags: ["unclear_contract", "management_poor", "communication_poor"],
    verificationStatus: "WORKER_REPORTED",
    sourceType: "WORKER_REPORTED",
    createdAt: "2025-09-05",
  },

  // ─── International Flex Job ────────────────────────────────────────────────
  {
    agencySlug:            "international-flex-job",
    reviewType:            "ANONYMOUS",
    title:                 "Bad experience — feels like a trap",
    overallRating:         2,
    salaryRating:          2,
    housingRating:         1,
    managementRating:      2,
    contractClarityRating: 2,
    comment:               "I'm working with International Flex Job right now and honestly it's bad. After paying €120 for accommodation, €36 for insurance, and €25 for transport, I end up with around €340 net per week. The house is in the middle of nowhere and we even had rats. I worked before with Covebo in Ceva Logistic and that was a much better experience. This one feels like a trap.",
    jobTitle:              null,
    city:                  null,
    issueTags:             ["housing_dirty", "housing_crowded", "below_average_pay", "communication_poor"],
    verificationStatus:    "WORKER_REPORTED",
    sourceType:            "WORKER_REPORTED",
    createdAt:             "2025-11-01",
  },

  // ─── Covebo ───────────────────────────────────────────────────────────────
  {
    agencySlug:            "covebo",
    reviewType:            "ANONYMOUS",
    title:                 "Stable experience at Ceva Logistic — better than most",
    overallRating:         4,
    salaryRating:          4,
    housingRating:         null,
    managementRating:      4,
    contractClarityRating: 4,
    comment:               "I've worked with Covebo before in Ceva Logistic and it was a good experience. Compared to other agencies, things were more stable and I didn't feel like I was getting screwed with hidden costs. Still not perfect, but definitely better than most.",
    jobTitle:              null,
    city:                  "Ceva Logistic",
    issueTags:             ["fair_pay", "management_ok"],
    verificationStatus:    "WORKER_REPORTED",
    sourceType:            "WORKER_REPORTED",
    createdAt:             "2025-11-01",
  },

  // ─── Westflex ─────────────────────────────────────────────────────────────
  {
    agencySlug:            "westflex",
    reviewType:            "ANONYMOUS",
    title:                 "Good money possible but hard work and unstable schedule",
    overallRating:         3,
    salaryRating:          4,
    housingRating:         null,
    managementRating:      3,
    contractClarityRating: 3,
    comment:               "Westflex can actually pay good money, up to €600–900 per week, but it's not easy. You'll be doing double shifts, weekends, and holidays. It's hard work and your schedule keeps changing. If you want money, it's possible here, but be ready to sacrifice your time and energy.",
    jobTitle:              null,
    city:                  "Aalsmeer",
    issueTags:             ["fair_pay", "management_ok", "communication_poor"],
    verificationStatus:    "WORKER_REPORTED",
    sourceType:            "WORKER_REPORTED",
    createdAt:             "2025-11-02",
  },

  // ─── NL Jobs ──────────────────────────────────────────────────────────────
  {
    agencySlug:            "nl-jobs",
    reviewType:            "ANONYMOUS",
    title:                 "50/50 — greenhouse and demolition work available",
    overallRating:         3,
    salaryRating:          3,
    housingRating:         3,
    managementRating:      3,
    contractClarityRating: 3,
    comment:               "I've seen people say NLJobs, Fix, and VZM are not bad, but it's really 50/50. Most jobs are greenhouse work. In VZM you can get demolition jobs (mustag), which pay better but are physically very hard. You usually get accommodation and sometimes a car if you have a license.",
    jobTitle:              null,
    city:                  null,
    issueTags:             ["housing_good", "transport_good"],
    verificationStatus:    "WORKER_REPORTED",
    sourceType:            "WORKER_REPORTED",
    createdAt:             "2025-11-03",
  },

  // ─── General housing experience (anonymous, multi-agency) ─────────────────
  {
    agencySlug:            "international-flex-job",
    reviewType:            "ANONYMOUS",
    title:                 "Agency accommodation — depends on luck",
    overallRating:         2,
    salaryRating:          3,
    housingRating:         1,
    managementRating:      2,
    contractClarityRating: 3,
    comment:               "I've lived in multiple agency accommodations. One time I had a basement room that was always moist. Another time I shared a tiny room where two beds barely fit. I also lived in a 5-person house. In many places there are no locks on the rooms, so you never feel safe. It really depends on luck.",
    jobTitle:              null,
    city:                  null,
    issueTags:             ["housing_dirty", "housing_crowded"],
    verificationStatus:    "WORKER_REPORTED",
    sourceType:            "WORKER_REPORTED",
    createdAt:             "2025-11-04",
  },

];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Group reviews by agency slug for easy lookup */
export function getReviewsByAgency(slug: string): ReviewSeed[] {
  return REVIEW_SEED_DATA.filter((r) => r.agencySlug === slug);
}

/** Compute average overall rating for a set of reviews (0 if empty) */
export function avgOverallRating(reviews: ReviewSeed[]): number {
  if (reviews.length === 0) return 0;
  return reviews.reduce((s, r) => s + r.overallRating, 0) / reviews.length;
}

/** Latest N reviews sorted by createdAt desc */
export function getLatestReviews(n = 5): ReviewSeed[] {
  return [...REVIEW_SEED_DATA]
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
    .slice(0, n);
}

/** Most common issue tags across all reviews */
export function getTopIssueTags(n = 6): { tag: string; count: number }[] {
  const counts: Record<string, number> = {};
  for (const r of REVIEW_SEED_DATA) {
    for (const t of r.issueTags) {
      counts[t] = (counts[t] ?? 0) + 1;
    }
  }
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([tag, count]) => ({ tag, count }));
}
