"""
AgencyCheck — generate-seed-data.py v2
Reads scripts/data/03_canonical_agencies.json and emits:
  lib/canonicalAgencies.ts  — typed TS array (CANONICAL_AGENCIES)
  lib/mockData.ts            — AgencyCardData array + helpers (AGENCIES, AGENCY_MAP, etc.)

Run after dedupe-pipeline.py:
  python3 scripts/dedupe-pipeline.py && python3 scripts/generate-seed-data.py
"""
import json, re, textwrap
from pathlib import Path
from datetime import date

CANONICAL_JSON = Path("scripts/data/03_canonical_agencies.json")
SUMMARY_JSON   = Path("scripts/data/00_summary.json")
OUT_CANONICAL  = Path("lib/canonicalAgencies.ts")
OUT_MOCK       = Path("lib/mockData.ts")

TODAY = date.today().isoformat()

agencies = json.loads(CANONICAL_JSON.read_text())
summary  = json.loads(SUMMARY_JSON.read_text())

print(f"Generating seed data for {len(agencies)} canonical agencies…")

# ─── helpers ──────────────────────────────────────────────────────────────────

def ts_str(v):
    """Python value → TypeScript string literal or null."""
    if v is None or v == "unknown" or v == "":
        return "null"
    escaped = str(v).replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f'"{escaped}"'

def ts_arr(lst):
    if not lst:
        return "[]"
    items = ", ".join(f'"{s}"' for s in lst)
    return f"[{items}]"

def ts_obj(d):
    if not d:
        return "{}"
    pairs = ", ".join(f'"{k}": "{v}"' for k, v in d.items())
    return f"{{ {pairs} }}"

def housing_enum(v):
    if v == "YES":   return "Housing.YES"
    if v == "NO":    return "Housing.NO"
    return "Housing.UNKNOWN"

def transport_enum(v):
    if v == "YES":   return "Transport.YES"
    if v == "NO":    return "Transport.NO"
    return "Transport.UNKNOWN"

def housing_type_enum(v):
    valid = {"SHARED_HOUSE", "PRIVATE_ROOM", "STUDIO", "APARTMENT", "UNKNOWN"}
    if v and v.upper() in valid:
        return f"HousingType.{v.upper()}"
    return "HousingType.UNKNOWN"

def source_type_enum(v):
    valid = {"ABU_REGISTER", "SNCU_REGISTER", "OFFICIAL_WEBSITE", "WORKER_REPORTED", "UNKNOWN"}
    if v and v.upper() in valid:
        return f"SourceType.{v.upper()}"
    return "SourceType.UNKNOWN"

def mock_housing(v):
    if v == "YES":   return '"YES"'
    if v == "NO":    return '"NO"'
    return '"UNKNOWN"'

# ─── emit canonicalAgencies.ts ────────────────────────────────────────────────

lines_canonical = [
    f"// Auto-generated by generate-seed-data.py — DO NOT EDIT MANUALLY",
    f"// Re-generate: python3 scripts/dedupe-pipeline.py && python3 scripts/generate-seed-data.py",
    f"// Generated: {TODAY}  |  {len(agencies)} canonical agencies  (from {summary['raw_rows_imported']} raw rows, {summary['duplicates_removed']} duplicates removed)",
    f"",
    f'import {{ Housing, Transport, HousingType, SourceType }} from "@prisma/client";',
    f"",
    f"export interface CanonicalAgencySeed {{",
    f"  canonicalId:             string;",
    f"  name:                    string;",
    f"  slug:                    string;",
    f"  website:                 string | null;",
    f"  city:                    string;",
    f"  cities:                  string[];",
    f"  housing:                 Housing;",
    f"  housingType:             HousingType;",
    f"  transport:               Transport;",
    f"  jobTypes:                string | null;",
    f"  salaryRange:             string | null;",
    f"  description:             string | null;",
    f"  aliases:                 string[];",
    f"  duplicateCount:          number;",
    f"  confidenceScore:         number;",
    f"  sourceUrl:               string | null;",
    f"  sourceType:              SourceType;",
    f"  webPages:                Record<string, string>;",
    f"  housingVerification:     Record<string, string>;",
    f"  transportVerification:   Record<string, string>;",
    f"}}",
    f"",
    f"export const CANONICAL_AGENCIES: CanonicalAgencySeed[] = [",
]

for a in agencies:
    hv = a.get("housing_verification", {})
    tv = a.get("transport_verification", {})
    # Ensure string values in verification objects
    hv_clean = {k: str(v) for k, v in hv.items() if v is not None}
    tv_clean = {k: str(v) for k, v in tv.items() if v is not None}

    lines_canonical.append("  {")
    lines_canonical.append(f"    canonicalId:           {ts_str(a['canonical_id'])},")
    lines_canonical.append(f"    name:                  {ts_str(a['agency_name'])},")
    lines_canonical.append(f"    slug:                  {ts_str(a['slug'])},")
    lines_canonical.append(f"    website:               {ts_str(a.get('website'))},")
    lines_canonical.append(f"    city:                  {ts_str(a.get('city','unknown'))},")
    lines_canonical.append(f"    cities:                {ts_arr(a.get('known_cities',[]))},")
    lines_canonical.append(f"    housing:               {housing_enum(a.get('housing','UNKNOWN'))},")
    lines_canonical.append(f"    housingType:           {housing_type_enum(a.get('housing_type','UNKNOWN'))},")
    lines_canonical.append(f"    transport:             {transport_enum(a.get('transport','UNKNOWN'))},")
    lines_canonical.append(f"    jobTypes:              {ts_str(a.get('job_types'))},")
    lines_canonical.append(f"    salaryRange:           {ts_str(a.get('salary_range'))},")
    lines_canonical.append(f"    description:           {ts_str(a.get('description'))},")
    lines_canonical.append(f"    aliases:               {ts_arr(a.get('aliases',[]))},")
    lines_canonical.append(f"    duplicateCount:        {a.get('duplicate_count',1)},")
    lines_canonical.append(f"    confidenceScore:       {a.get('confidence_score',100)},")
    lines_canonical.append(f"    sourceUrl:             {ts_str(a.get('source_url'))},")
    lines_canonical.append(f"    sourceType:            {source_type_enum(a.get('source_type','UNKNOWN'))},")
    lines_canonical.append(f"    webPages:              {ts_obj(a.get('web_pages',{}))},")
    lines_canonical.append(f"    housingVerification:   {ts_obj(hv_clean)},")
    lines_canonical.append(f"    transportVerification: {ts_obj(tv_clean)},")
    lines_canonical.append("  },")

lines_canonical.append("];")
lines_canonical.append("")
lines_canonical.append("export default CANONICAL_AGENCIES;")
lines_canonical.append("")

OUT_CANONICAL.write_text("\n".join(lines_canonical))
print(f"✓ {OUT_CANONICAL}  ({OUT_CANONICAL.stat().st_size // 1024}KB)")

# ─── emit mockData.ts ─────────────────────────────────────────────────────────

lines_mock = [
    f"// Auto-generated by generate-seed-data.py — DO NOT EDIT MANUALLY",
    f"// Re-generate: python3 scripts/dedupe-pipeline.py && python3 scripts/generate-seed-data.py",
    f"// Generated: {TODAY}  |  {len(agencies)} agencies",
    f"",
    f"/**",
    f" * AgencyCardData — lightweight UI-facing agency record.",
    f" * Subset of CanonicalAgencySeed, no Prisma enums (plain strings for client components).",
    f" */",
    f"export interface AgencyCardData {{",
    f'  id:                    string;',
    f'  name:                  string;',
    f'  slug:                  string;',
    f'  description:           string | null;',
    f'  website:               string | null;',
    f'  housing:               "YES" | "NO" | "UNKNOWN";',
    f'  transport:             "YES" | "NO" | "UNKNOWN";',
    f'  city:                  string;',
    f'  cities:                string[];',
    f'  score:                 number;',
    f'  reviewCount:           number;',
    f'  avgSalaryRating:       number | null;',
    f'  avgHourlyPay:          number | null;',
    f'  avgHousingRating:      number | null;',
    f'  issueCount:            number;',
    f'  jobTitles:             string[];',
    f'  aliases:               string[];',
    f'  jobTypes:              string | null;',
    f'  sourceUrl:             string | null;',
    f'  webPages:              Record<string, string>;',
    f'  housingVerification:   {{ value: string; status: string; source_url: string; source_type: string }};',
    f'  transportVerification: {{ value: string; status: string; source_url: string; source_type: string }};',
    f'}}',
    f'',
    f'export const AGENCIES: AgencyCardData[] = [',
]

for a in agencies:
    hv = a.get("housing_verification", {})
    tv = a.get("transport_verification", {})
    hv_str = ts_obj({k: str(v) for k, v in hv.items() if v is not None})
    tv_str = ts_obj({k: str(v) for k, v in tv.items() if v is not None})
    web_str = ts_obj(a.get("web_pages", {}))

    # job titles from job_types string
    jt = a.get("job_types") or ""
    job_titles = [p.strip() for p in re.split(r"[,/]", jt) if p.strip() and p.strip().lower() != "unknown"] if jt else []

    lines_mock.append("  {")
    lines_mock.append(f"    id:                    {ts_str(a['canonical_id'])},")
    lines_mock.append(f"    name:                  {ts_str(a['agency_name'])},")
    lines_mock.append(f"    slug:                  {ts_str(a['slug'])},")
    lines_mock.append(f"    description:           {ts_str(a.get('description'))},")
    lines_mock.append(f"    website:               {ts_str(a.get('website'))},")
    lines_mock.append(f"    housing:               {mock_housing(a.get('housing','UNKNOWN'))},")
    lines_mock.append(f"    transport:             {mock_housing(a.get('transport','UNKNOWN'))},")
    lines_mock.append(f"    city:                  {ts_str(a.get('city','unknown'))},")
    lines_mock.append(f"    cities:                {ts_arr(a.get('known_cities',[]))},")
    lines_mock.append(f"    score:                 100,")
    lines_mock.append(f"    reviewCount:           0,")
    lines_mock.append(f"    avgSalaryRating:       null,")
    lines_mock.append(f"    avgHourlyPay:          null,")
    lines_mock.append(f"    avgHousingRating:      null,")
    lines_mock.append(f"    issueCount:            0,")
    lines_mock.append(f"    jobTitles:             {ts_arr(job_titles)},")
    lines_mock.append(f"    aliases:               {ts_arr(a.get('aliases',[]))},")
    lines_mock.append(f"    jobTypes:              {ts_str(a.get('job_types'))},")
    lines_mock.append(f"    sourceUrl:             {ts_str(a.get('source_url'))},")
    lines_mock.append(f"    webPages:              {web_str},")
    lines_mock.append(f"    housingVerification:   {hv_str},")
    lines_mock.append(f"    transportVerification: {tv_str},")
    lines_mock.append("  },")

lines_mock += [
    "];",
    "",
    "/** O(1) slug lookup */",
    "export const AGENCY_MAP: Record<string, AgencyCardData> =",
    "  Object.fromEntries(AGENCIES.map((a) => [a.slug, a]));",
    "",
    "/** Agencies that confirmed housing availability */",
    "export const AGENCIES_WITH_HOUSING = AGENCIES.filter((a) => a.housing === \"YES\");",
    "",
    "/** Agencies that confirmed transport availability */",
    "export const AGENCIES_WITH_TRANSPORT = AGENCIES.filter((a) => a.transport === \"YES\");",
    "",
    "/** Legacy alias — prefer AGENCIES */",
    "export const MOCK_AGENCIES = AGENCIES;",
    "",
]

OUT_MOCK.write_text("\n".join(lines_mock))
print(f"✓ {OUT_MOCK}  ({OUT_MOCK.stat().st_size // 1024}KB)")

# Quick validation
import subprocess, sys
result = subprocess.run(
    ["node", "--input-type=module", "-e", ""],
    input="", capture_output=True, text=True
)

# Count entries
canonical_count = sum(1 for l in OUT_CANONICAL.read_text().splitlines() if l.strip() == "},")
mock_count      = sum(1 for l in OUT_MOCK.read_text().splitlines() if l.strip() == "},")
print(f"\nValidation:")
print(f"  canonicalAgencies.ts: {canonical_count} entries")
print(f"  mockData.ts:          {mock_count} entries")
if canonical_count != len(agencies):
    print(f"  ⚠️  Expected {len(agencies)}, got {canonical_count}")
else:
    print(f"  ✓ Entry count matches canonical ({len(agencies)})")
